### ISSUE TITLE
JSON stapler stopped working. At the same time JSON is valid.

### ISSUE THREAD

**Issue by flymedllva** [wundergraph/cosmo#1084]
### Component(s)

router

### Component version

v0.105.0

### wgc version

v0.58.5

### controlplane version

-

### router version

v0.105.0

## Description

After recent router updates, the JSON stapler stopped working for some valid JSON

## Steps to Reproduce

Fork example

In order to reproduce, clone the repository and start the router
https://github.com/flymedllva/cosmo-broken-json-stapler

Run Query:
```graphql
query Test {
  test {
    data
  }
}
```

## Expected Result
Valid JSON (weird, though)
```json
{
  "data": {
    "test": {
      "data": "\u0015"
    }
  }
}
```

## Actual Result
```json
{
  "errors": [
    {
      "message": "Bad escaped character in JSON at position 26 (line 1 column 27)",
      "stack": "SyntaxError: Bad escaped character in JSON at position 26 (line 1 column 27)"
    }
  ]
}
```

**With another variation** of the query (many fields), the error may not occur, but the **encoding will change** `\u0015` -> `\x15`

<img width="142" alt="Screenshot 2024-08-15 at 23 05 21" src="https://github.com/user-attachments/assets/2f9f836f-7606-4133-aafd-c21407c9ea87">

## Environment
OS: (e.g., "Ubuntu 20.04") macOS
Package Manager: pnpm, npm, yarn, etc pnpm 
Compiler(if manually compiled): (e.g., "go 14.2") go version go1.22.5 darwin/arm64

### Router configuration

```yaml
version: "1"

# General router options
graph:
  token: ""

log_level: "info"
listen_addr: "localhost:3002"
playground_enabled: true
introspection_enabled: true
json_log: true
shutdown_delay: 15s
grace_period: 20s
poll_interval: 10s
health_check_path: "/health"
readiness_check_path: "/health/ready"
liveness_check_path: "/health/live"
router_config_path: "config.json"

cors:
  allow_origins: ["*"]
  allow_methods:
    - HEAD
    - GET
    - POST
  allow_headers:
    - Origin
    - Content-Length
    - Content-Type
  allow_credentials: true

# Config for custom modules   
# See "https://cosmo-docs.wundergraph.com/router/custom-modules" for more information   
modules:
  myModule:
    # Arbitrary values, unmarshalled by the module
    value: 1
```
