### ISSUE TITLE
Apollo compatibility broke, mandatory arguments stopped supporting default values from the schema.

### ISSUE THREAD

**Issue by flymedllva** [wundergraph/cosmo#1085]
### Component(s)

router

### Component version

v0.105.0

### wgc version

v0.58.5

### controlplane version

-

### router version

v0.105.0

## Description

After recent updates to the router, with the tightening when dealing with the circuitry broke Apollo compatibility, even though it seems to be more descriptive of the GraphQL specification.
I have a broken load of about 3000 variations of the queries.

## Steps to Reproduce

Fork example

In order to reproduce, clone the repository and start the router
https://github.com/flymedllva/cosmo-standard-values-of-mandatory-arguments-are-broken

Run Query
```graphql
query Test {
  test(input: {
    filter: {
      # empty
    }
  }) {
    a
    b
  }
}
```
for schema
```graphql
type Query {
  test(input: TestInput!): TestResult!
}

input TestFilterInput {
  a: Int
  b: Int! = 123
}

input TestInput {
  filter: TestFilterInput
}

type TestResult {
  a: Int
  b: Int!
}
```

## Expected Result
```json
{
  "data": {
    "test": {
      "a": null,
      "b": 123
    }
  }
}
```

## Actual Result
```json
{
  "errors": [
    {
      "message": "Variable \"$a\" got invalid value {\"filter\":{}}; Field \"b\" of required type \"Int!\" was not provided."
    }
  ],
  "data": null
}
```

## Environment
OS: (e.g., "Ubuntu 20.04") macOS
Package Manager: pnpm, npm, yarn, etc pnpm 
Compiler(if manually compiled): (e.g., "go 14.2") go version go1.22.5 darwin/arm64

### Router configuration

```yaml
version: "1"

# General router options
graph:
  token: ""

log_level: "info"
listen_addr: "localhost:3002"
playground_enabled: true
introspection_enabled: true
json_log: true
shutdown_delay: 15s
grace_period: 20s
poll_interval: 10s
health_check_path: "/health"
readiness_check_path: "/health/ready"
liveness_check_path: "/health/live"
router_config_path: "config.json"

cors:
  allow_origins: ["*"]
  allow_methods:
    - HEAD
    - GET
    - POST
  allow_headers:
    - Origin
    - Content-Length
    - Content-Type
  allow_credentials: true

# Config for custom modules   
# See "https://cosmo-docs.wundergraph.com/router/custom-modules" for more information   
modules:
  myModule:
    # Arbitrary values, unmarshalled by the module
    value: 1
```
