### ISSUE TITLE
ServiceName column missing in the Otel Table in Clickhouse

### ISSUE THREAD

**Issue by anmolghosh** [wundergraph/cosmo#1166]
### Component(s)

otelcollector

### Component version

0.17.1

### wgc version

0.40.2

### controlplane version

0.107.0

### router version

0.109.1

## Description
We have Cosmo deployed inside kubernetes cluster using the standard helm chart provided by Wundergraph team. When we are looking at the logs of otelcollector, we see following errors 

```
insert sum metrics fail:code: 16, message: No such column ServiceName in table cosmo.otel_metrics_sum
insert gauge metrics fail:code: 16, message: No such column ServiceName in table cosmo.otel_metrics_gauge
insert histogram metrics fail:code: 16, message: No such column ServiceName in table cosmo.otel_metrics_histogram
```
Running a count query on the above table table inside clickhouse show all 3 tables have zero record.

Also, if we review the schema on the following file, we can verify that the column `ServiceName` was never defined in first place
https://github.com/wundergraph/cosmo/blob/main/controlplane/db/schema.sql

## Steps to Reproduce
Install Wundergraph cosmo using the standard helm chart with otelcollector enabled
Prometheus is kept disabled on all components.

## Expected Result
There are no errors in otelcollector logs and records are being inserted into corresponding clickhouse tables

## Actual Result

All inserts to otel_metrics_sum, otel_metrics_gauge and otel_metrics_histogram are failing with error
```
 No such column ServiceName in table
```

## Environment
WunderGraph Cosmo Stack running on AWS EKS Kubernetes Cluster. 
Stack deployed using helm chart
```
oci://ghcr.io/wundergraph/cosmo/helm-charts/cosmo
```
Versions:

> Helm Chart: 0.11.1
> cdn: 0.10.1
> controlplane: 0.107.0
> studio: 0.88.1
> router: 0.109.1
> otelcollector: 0.17.1
> graphqlmetrics: 0.22.0

### Router configuration

```yaml
version: "1"
headers:
  all: # Header rules for all origin requests.
    request:
      - op: "propagate"
        named: Authorization
      - op: "propagate"
        named: ClientKey
      - op: "propagate"
        named: refresh_token
      - op: "propagate"
        named: Traceparent
subgraph_error_propagation:
  enabled: true
  mode: "pass-through"
traffic_shaping:
  all:
    request_timeout: 120s
cors:
  allow_headers:
    - Origin
    - Content-Length
    - Content-Type
    - ClientKey
    - Refresh_Token
```

### Log output

```shell
2024-09-13T00:56:28+05:30 {"level":"info","ts":1726169188.0839438,"caller":"exporterhelper/retry_sender.go:118","msg":"Exporting failed. Will retry the request after interval.","kind":"exporter","data_type":"metrics","name":"clickhouse","error":"insert sum metrics fail:code: 16, message: No such column ServiceName in table cosmo.otel_metrics_sum (fa3d81a4-19e7-4ef0-9832-dabab1acd4c5)\ninsert gauge metrics fail:code: 16, message: No such column ServiceName in table cosmo.otel_metrics_gauge (a3cb4634-2048-4bad-9ac6-8828c9631d21)\ninsert histogram metrics fail:code: 16, message: No such column ServiceName in table cosmo.otel_metrics_histogram (edbfb99c-5432-418d-875c-1538d263e1f8)","interval":"35.094430427s"}
2024-09-13T00:57:03+05:30 {"level":"info","ts":1726169223.1858504,"caller":"exporterhelper/retry_sender.go:118","msg":"Exporting failed. Will retry the request after interval.","kind":"exporter","data_type":"metrics","name":"clickhouse","error":"insert gauge metrics fail:code: 16, message: No such column ServiceName in table cosmo.otel_metrics_gauge (a3cb4634-2048-4bad-9ac6-8828c9631d21)\ninsert sum metrics fail:code: 16, message: No such column ServiceName in table cosmo.otel_metrics_sum (fa3d81a4-19e7-4ef0-9832-dabab1acd4c5)\ninsert histogram metrics fail:code: 16, message: No such column ServiceName in table cosmo.otel_metrics_histogram (edbfb99c-5432-418d-875c-1538d263e1f8)","interval":"18.860788202s"}
```
