### ISSUE TITLE
In the new version BatchEntityFetch stopped working adequately with some variation of composite key/resolvable: false/sharable

### ISSUE THREAD

**Issue by flymedllva** [wundergraph/cosmo#1184]
### Component(s)

router

### Component version

0.110.1

### wgc version

0.64.1

### controlplane version

-

### router version

0.110.1

## Description

In the new version BatchEntityFetch stopped working adequately with some variation of composite keys, resolvable false, sharable

## Steps to Reproduce

Use the schema I sent you in the mail
https://github.com/wundergraph/cosmo/issues/959#issuecomment-2258868305

Run Query:
```graphql
query TestidentificationReports {
  identificationReports(
    filter: {
      idIn: "123456789"
    }
    page: 1
    perPage: 1
    sort: ORDER_CREATED_AT
    sortDirection: DESC
  ) {
    items {
      event {
        documents {
          document {
            payeeAmount
          }
        }
      }
    }
  }
}
```

## Expected Result
Working Query as in the old version of cosmo or apollo.

## Actual Result
```json
{
  "message": "expected at least one definition, found }",
  "extensions": {
    "code": "GRAPHQL_PARSE_FAILED"
  }
}
```

Also, the Query Plan does not always work, probably for the same reason
Sometimes **subgraphs** from cosmo **receive broken JSONs**

By doing a variation Query I achieved a working plan and saw there this
![Screenshot 2024-09-18 at 11 11 00](https://github.com/user-attachments/assets/07195ba6-ecd2-47b3-b928-0c731e899541)

## Environment
OS: (e.g., "Ubuntu 20.04") macOS
Package Manager: pnpm, npm, yarn, etc pnpm 
Compiler(if manually compiled): (e.g., "go 14.2") go version go1.22.5 darwin/arm64

### Router configuration

```yaml
version: "1"

# General router options
graph:
  token: ""

log_level: "info"
listen_addr: "localhost:3002"
playground_enabled: true
introspection_enabled: true
json_log: true
shutdown_delay: 15s
grace_period: 20s
poll_interval: 10s
health_check_path: "/health"
readiness_check_path: "/health/ready"
liveness_check_path: "/health/live"
router_config_path: "config.json"

cors:
  allow_origins: ["*"]
  allow_methods:
    - HEAD
    - GET
    - POST
  allow_headers:
    - Origin
    - Content-Length
    - Content-Type
  allow_credentials: true

# Config for custom modules   
# See "https://cosmo-docs.wundergraph.com/router/custom-modules" for more information   
modules:
  myModule:
    # Arbitrary values, unmarshalled by the module
    value: 1
```

### Log output

```shell
\nDownstream errors:\n1. Subgraph error with Message: expected at least one definition, found }, Extension Code: GRAPHQL_PARSE_FAILED.
```
