### ISSUE TITLE
Panic when trying to use initialPayload ExportToken config

### ISSUE THREAD

**Issue by ElliottZeroFlucs** [wundergraph/cosmo#1238]
### Component(s)

router

### Component version

0.116.3

### wgc version

0.66.2

### controlplane version

0.110.0

### router version

0.116.3

## Description
When trying to use subscriptions we need to use the `fromInitialPayloadConfig.ExportToken.Enabled` config to export the token from the initial payload to the request header. We do not need the `accessController.Access` check and haven't configured any authenticators. We would expect that if authentication was not enabled and no authenticators provided the token export should still be able to run.

We have found that there is a missing nil check for the accessController and so there is a panic, nil pointer dereference error.

Further up in the `handleUpgradeRequest` you can see the nil check is in place.
https://github.com/wundergraph/cosmo/blob/main/router/core/websocket.go#L236

Here the nil check is missing and this is what causes the panic. With the correct nil check our use case works as expected.
https://github.com/wundergraph/cosmo/blob/main/router/core/websocket.go#L343

## Steps to Reproduce
1. Setup a router with acess to a subgraph containing a subscription.
2. Setup websocket config with the from_initial_payload.export_token enabled. (Don't setup any authenticators)
3. Run the router.
4. Create a subscription in the playground.
5. The panic will occur.

## Expected Result
The subscription should be created successfully.

## Actual Result
The router panics.

## Environment
OS: (e.g., "MacOS 13.5")
Package Manager: pnpm
Compiler(if manually compiled): "go 1.23.1"

### Router configuration

```yaml
# yaml-language-server: $schema=./pkg/config/config.schema.json

# See pkg/config/config.go for the full list of configuration options.
# This file is used to debugging purposes only.

version: "1"

router_config_path: "./__schemas/config.json"

engine:
  max_concurrent_resolvers: 1024
  debug:
    report_websocket_connections: true
    report_memory_usage: true

websocket:
  enabled: true
  forward_initial_payload: true
  authentication:
    from_initial_payload:
      enabled: true
      key: Authorization
      export_token:
        enabled: true
        header_key: Authorization

events:
  providers:
    nats:
      - id: default
        url: "nats://localhost:4222"
      - id: my-nats
        url: "nats://localhost:4222"
    kafka:
      - id: my-kafka
        brokers:
          - "localhost:9092"

headers:
  all:
    request:
      - op: "propagate"            
        named: Authorization
```

### Log output

```shell
13:22:07 PM ERROR [Recovery from panic] {"hostname": "MacBook-Air-2.local", "pid": 52812, "component": "@wundergraph/router", "service_version": "dev", "method": "GET", "path": "/graphql", "query": "", "ip": "[REDACTED]", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36", "config_version": "e4482b68-d02b-4f09-af09-6d0f07e212be", "request_id": "MacBook-Air-2.local/SXsUjBBg68-000003", "status": 500, "latency": 0.000720292, "error": "runtime error: invalid memory address or nil pointer dereference"}
github.com/wundergraph/cosmo/router/internal/requestlogger.(*handler).ServeHTTP.func1
        /Users/username/go/src/github.com/wundergraph/cosmo/router/internal/requestlogger/requestlogger.go:189
runtime.gopanic
        /Users/username/.brew/Cellar/go/1.23.1/libexec/src/runtime/panic.go:785
runtime.panicmem
        /Users/username/.brew/Cellar/go/1.23.1/libexec/src/runtime/panic.go:262
runtime.sigpanic
        /Users/username/.brew/Cellar/go/1.23.1/libexec/src/runtime/signal_unix.go:900
net/http.(*Request).Context
        /Users/username/.brew/Cellar/go/1.23.1/libexec/src/net/http/request.go:352
github.com/wundergraph/cosmo/router/core.(*AccessController).Access
        /Users/username/go/src/github.com/wundergraph/cosmo/router/core/access_controller.go:34
github.com/wundergraph/cosmo/router/core.(*WebsocketHandler).handleUpgradeRequest
        /Users/username/go/src/github.com/wundergraph/cosmo/router/core/websocket.go:345
github.com/wundergraph/cosmo/router/core.NewWebsocketMiddleware.func1.1
        /Users/username/go/src/github.com/wundergraph/cosmo/router/core/websocket.go:140
net/http.HandlerFunc.ServeHTTP
        /Users/username/.brew/Cellar/go/1.23.1/libexec/src/net/http/server.go:2220
github.com/wundergraph/cosmo/router/internal/requestlogger.(*handler).ServeHTTP
        /Users/username/go/src/github.com/wundergraph/cosmo/router/internal/requestlogger/requestlogger.go:199
github.com/wundergraph/cosmo/router/pkg/trace.(*Middleware).Handler.func1
        /Users/username/go/src/github.com/wundergraph/cosmo/router/pkg/trace/middleware.go:52
net/http.HandlerFunc.ServeHTTP
        /Users/username/.brew/Cellar/go/1.23.1/libexec/src/net/http/server.go:2220
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*middleware).serveHTTP
        /Users/username/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.46.1/handler.go:143
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.NewMiddleware.func1.1
        /Users/username/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.46.1/handler.go:81
net/http.HandlerFunc.ServeHTTP
        /Users/username/.brew/Cellar/go/1.23.1/libexec/src/net/http/server.go:2220
github.com/wundergraph/cosmo/router/core.(*graphServer).buildGraphMux.func5.1
        /Users/username/go/src/github.com/wundergraph/cosmo/router/core/graph_server.go:522
net/http.HandlerFunc.ServeHTTP
        /Users/username/.brew/Cellar/go/1.23.1/libexec/src/net/http/server.go:2220
github.com/wundergraph/cosmo/router/core.(*graphServer).buildGraphMux.func4.1
        /Users/username/go/src/github.com/wundergraph/cosmo/router/core/graph_server.go:503
net/http.HandlerFunc.ServeHTTP
        /Users/username/.brew/Cellar/go/1.23.1/libexec/src/net/http/server.go:2220
github.com/go-chi/chi/v5.(*Mux).ServeHTTP
        /Users/username/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.11/mux.go:73
net/http.HandlerFunc.ServeHTTP
        /Users/username/.brew/Cellar/go/1.23.1/libexec/src/net/http/server.go:2220
github.com/go-chi/chi/v5.(*Mux).Mount.func1
        /Users/username/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.11/mux.go:315
net/http.HandlerFunc.ServeHTTP
        /Users/username/.brew/Cellar/go/1.23.1/libexec/src/net/http/server.go:2220
github.com/klauspost/compress/gzhttp.NewWrapper.func1.1
        /Users/username/go/pkg/mod/github.com/klauspost/compress@v1.17.9/gzhttp/compress.go:495
net/http.HandlerFunc.ServeHTTP
        /Users/username/.brew/Cellar/go/1.23.1/libexec/src/net/http/server.go:2220
github.com/go-chi/chi/v5.(*ChainHandler).ServeHTTP
        /Users/username/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.11/chain.go:31
github.com/go-chi/chi/v5.(*Mux).routeHTTP
        /Users/username/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.11/mux.go:443
net/http.HandlerFunc.ServeHTTP
        /Users/username/.brew/Cellar/go/1.23.1/libexec/src/net/http/server.go:2220
github.com/wundergraph/cosmo/router/pkg/cors.(*cors).ServeHTTP
        /Users/username/go/src/github.com/wundergraph/cosmo/router/pkg/cors/config.go:74
github.com/go-chi/chi/v5/middleware.RealIP.func1
        /Users/username/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.11/middleware/realip.go:36
net/http.HandlerFunc.ServeHTTP
        /Users/username/.brew/Cellar/go/1.23.1/libexec/src/net/http/server.go:2220
github.com/go-chi/chi/v5/middleware.RequestID.func1
        /Users/username/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.11/middleware/request_id.go:76
net/http.HandlerFunc.ServeHTTP
        /Users/username/.brew/Cellar/go/1.23.1/libexec/src/net/http/server.go:2220
github.com/wundergraph/cosmo/router/core.newGraphServer.RequestSize.func9.1
        /Users/username/go/src/github.com/wundergraph/cosmo/router/internal/middleware/request_size.go:14
net/http.HandlerFunc.ServeHTTP
        /Users/username/.brew/Cellar/go/1.23.1/libexec/src/net/http/server.go:2220
github.com/wundergraph/cosmo/router/internal/recoveryhandler.(*handler).ServeHTTP
        /Users/username/go/src/github.com/wundergraph/cosmo/router/internal/recoveryhandler/recovery.go:39
github.com/go-chi/chi/v5.(*Mux).ServeHTTP
        /Users/username/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.11/mux.go:90
github.com/wundergraph/cosmo/router/core.newServer.func1
        /Users/username/go/src/github.com/wundergraph/cosmo/router/core/http_server.go:62
net/http.HandlerFunc.ServeHTTP
        /Users/username/.brew/Cellar/go/1.23.1/libexec/src/net/http/server.go:2220
net/http.serverHandler.ServeHTTP
        /Users/username/.brew/Cellar/go/1.23.1/libexec/src/net/http/server.go:3210
net/http.(*conn).serve
        /Users/username/.brew/Cellar/go/1.23.1/libexec/src/net/http/server.go:2092
```
