### ISSUE TITLE
Memory leak in introspection

### ISSUE THREAD

**Issue by ZirgVoice** [wundergraph/cosmo#1256]
### Component(s)

router

### Component version

v0.121.1

### wgc version

v0.67.0

### controlplane version

-

### router version

v0.121.1

## Description
When a constant introspection request is made, memory leakage occurs.

## Steps to Reproduce
The simplest way is to open `Apollo GraphQL Studio` and enable `Auto Update` in the `Connection settings`. The sandbox will start sending an introspection request every second, and at that moment, you can observe a rapid increase in RAM usage. After disabling auto-update, the memory gradually clears up.

### Environment information

```env
FEDERATED_GRAPH_NAME=production
LISTEN_ADDR=0.0.0.0:3001
ROUTER_CONFIG_PATH=./config.json
METRICS_OTLP_ENABLED=false
PROMETHEUS_ENABLED=false
LOG_LEVEL=debug
DEV_MODE=true
```

### Router configuration

```yaml
cors:
  allow_origins: ["https://studio.apollographql.com", "http://gateway:4000", "https://localhost:4200"]
  allow_methods:
    - OPTIONS
    - GET
    - POST
  allow_headers:
    - Origin
    - Content-Length
    - Content-Type
  allow_credentials: true
headers:
  all:
    request:
      - op: "propagate"
        named: Authorization
telemetry:
  tracing:
    enabled: false
engine:
    minify_subgraph_operations: false
```
