### ISSUE TITLE
CORS specified allowed origins not working

### ISSUE THREAD

**Issue by cs-clarence** [wundergraph/cosmo#135]
I'm using the router locally and I have the following cors config:

```yaml
cors:
  allow_origins:
    - http://localhost:3000
    - https://localhost:3000
  allow_methods:
    - HEAD
    - GET
    - POST
  allow_headers:
    - Authorization
    - Origin
    - Content-Length
    - Content-Type
  allow_credentials: true
  max_age_minutes: 5m
```

But I am still getting a cors error, the response headers don't include the specified origins:
![image](https://github.com/wundergraph/cosmo/assets/71768661/5a2abc97-a06c-454b-8912-ac13cd94a7f2)

The request headers have the origin:
![image](https://github.com/wundergraph/cosmo/assets/71768661/7765a865-9c0c-450f-b295-333927925b6d)
