### ISSUE TITLE
Request body buffer not correctly cleared under heavy load

### ISSUE THREAD

**Issue by alexus37** [wundergraph/cosmo#1430]
### Component(s)

router

### Component version

v0.0.0-20240927172855-3e390cd5cf6c

### wgc version

None

### controlplane version

None

### router version

v0.0.0-20240927172855-3e390cd5cf6c

## Description

We created a test script written in go that iterates for a list of test queries and uses go routines to make requests to the router which is running on the same machine. For some of the those requests this [line](https://github.com/wundergraph/cosmo/blob/main/router/core/graphql_prehandler.go#L416) raise the following graphQL error:

```json
{"errors":[{"message":"error parsing request body: invalid character '{' after top-level value"}]}
```

when I look at the `httpOperation.body` I am seeing two post bodies inside eg. 

```json
"{\"query\": \"query {\\n  rateLimit {\\n    limit\\n    remaining\\n    resetAt\\n  }\\n}\"}{\"query\": \"query GetRepositoryMergeQueue {\\n  repository(owner: \\\"<REDACTED>\\\", name: \\\"<REDACTED>\\\") {\\n    mergeQueue {\\n      id\\n    }\\n  }\\n}\"}"
```

However, when I check what request is being received there is only 1 query in the body. It seems that the ReadBody function [here](https://github.com/wundergraph/cosmo/blob/main/router/core/operation_processor.go#L1117) is appending the new query to the buffer where the old query is already in. I am not sure if I need to start the router somehow differently or if I missed something else? When I do the requests sequentially I do not encounter this issue.

## Steps to Reproduce

Create a script which uses go routines to target the router. I can pretty consistently reproduce it with 100 queries in total. The router fails on different queries so it seems there is some kind of race condition involved. 

## Expected Result

Have only the current post body in the buffer

## Actual Result

The previous post body is still present in the buffer and the request fails.

## Environment
OS: (e.g., "Ubuntu 20.04")
Package Manager: pnpm, npm, yarn, etc
Compiler(if manually compiled): (e.g., "go 14.2")

### Router configuration

```yaml
version: "1"

dev_mode: true
listen_addr: 0.0.0.0:13002
execution_config:
  file:
    watch: true
    path: dev.supergraph.json

modules:
  custom-module-id:
    module-input-var: 2

# See https://cosmo-docs.wundergraph.com/router/proxy-capabilities#forward-http-headers-to-subgraphs
headers:
  all:
    request:
      - op: "propagate"
        named: Authorization
```

### Router execution config

```json

```

### Log output

```shell

```

### Additional context

We are only looking at query plans so all the requests are executed with these headers

```
{
  "X-WG-TRACE": "false",
  "X-WG-Skip-Loader": "true",
  "X-WG-Include-Query-Plan": "true",
}
```
