### ISSUE TITLE
ratelimit reject_status_code  not work

### ISSUE THREAD

**Issue by chensunny** [wundergraph/cosmo#1606]
### Component(s)

router

### Component version

router@0.181.1

### wgc version

0.71.1

### controlplane version

cloud

### router version

router@0.181.1

### What happened?

If possible, please create a PR with a failing test to illustrate the issue clearly.
Otherwise, please attach a minimum reproduction through a GitHub repository that includes
essential information such as the relevant subgraph SDLs.
Please also make sure that the instructions for the reproduction are clear, tested, and fully accurate.

## Description

config of ratelimit

```
  simple_strategy:
    rate: 1
    burst: 1
    period: 10s
    reject_exceeding_requests: false
    reject_status_code: 429
    hide_stats_from_response_extension: false
  storage:
    cluster_enabled: true
    urls:
      - "redis://localhost:9000"
      - "redis://localhost:9001"
      - "redis://localhost:9002"
      - "redis://localhost:9003"
      - "redis://localhost:9004"
      - "redis://localhost:9005"
    key_prefix: "cosmo_rate_limit"
  debug: true
  key_suffix_expression:  "request.header.Get('am-account-id') ?? request.header.Get('X-Forwarded-For')"
  error_extension_code:
    enabled: true
    code: "RATE_LIMIT_EXCEEDED"
```

## Steps to Reproduce

request 2 times for cloud demo

```
query MyQuery {
  employeeAsList (id: 10) {
    id
    # products
    # currentMood
  }
}
```

## Expected Result

return 429 HTTP status

## Actual Result

1. return 200 HTTP status
2.  retryAfterMs is error
 ```
 "extensions": {
    "rateLimit": {
      "key": "cosmo_rate_limit:1111",
      "requestRate": 1,
      "remaining": 0,
      "retryAfterMs": 1234,
      "resetAfterMs": 1234
    },
```

## Environment
OS: MacOS
Package Manager: pnpm, npm, yarn, etc
Compiler:go version go1.23.4 darwin/arm64

### Router configuration

```yaml
# yaml-language-server: $schema=./pkg/config/config.schema.json

# See pkg/config/config.go for the full list of configuration options.
# This file is used to debugging purposes only.

version: "1"

## Base
listen_addr: "0.0.0.0:8080"
dev_mode: true
shutdown_delay: 15s
grace_period: 15s

## Security
playground_enabled: true
introspection_enabled: true
query_plans_enabled: false

security:
  block_subscriptions:
    enabled: true
  complexity_calculation_cache: # This is for a local in-memory cache, to persist the calculation results
    enabled: true
    size: 5120
  complexity_limits:
    depth: # the equivalent of `security.depth_limit` prevoiusly
      enabled: false
      limit: 10
      ignore_persisted_operations: true
    total_fields:
      enabled: true
      limit: 128
      ignore_persisted_operations: true
    root_fields:
      enabled: true
      limit: 10
      ignore_persisted_operations: true
    root_field_aliases:
      enabled: false
      ignore_persisted_operations: true


### Rate Limit
#rate_limit:
#  enabled: false
#  strategy: "simple"
#  simple_strategy:
#    rate: 10
#    burst: 10
#    period: 1s
#    reject_exceeding_requests: false
#    reject_status_code: 429
#    hide_stats_from_response_extension: false
#  storage:
#    url: "redis://localhost:6379" #redis://user:password@localhost:6789/3?dial_timeout=3&db=1&read_timeout=6s&max_retries=2
#    key_prefix: "cosmo_rate_limit"
#  debug: true
#  key_suffix_expression: "request.header.Get('am-account-id') ?? request.header.Get('X-Forwarded-For')"
#  error_extension_code:
#    enabled: true
#    code: "RATE_LIMIT_EXCEEDED"

rate_limit:
  enabled: true
  strategy: "simple"
  simple_strategy:
    rate: 1
    burst: 1
    period: 10s
    reject_exceeding_requests: false
    reject_status_code: 429
    hide_stats_from_response_extension: false
  storage:
    cluster_enabled: true
    urls:
      - "redis://localhost:9000"
      - "redis://localhost:9001"
      - "redis://localhost:9002"
      - "redis://localhost:9003"
      - "redis://localhost:9004"
      - "redis://localhost:9005"

#      - "redis://test2:testpass@localhost:8001"
#      - "redis://test2:testpass@localhost:8001"
    key_prefix: "cosmo_rate_limit"
  debug: true
  key_suffix_expression:  "request.header.Get('am-account-id') ?? request.header.Get('X-Forwarded-For')"
  error_extension_code:
    enabled: true
    code: "RATE_LIMIT_EXCEEDED"



##  OpenTelemetry Tracing&&Mertics
telemetry:
  metrics:
    prometheus:
      listen_addr: "0.0.0.0:10000"
  tracing:
    propagation:
      trace_context: true


# PII data redaction
compliance:
  anonymize_ip:
    enabled: true
    method: redact # hash or redact

# Traffic Shaping is a set of options to control the traffic shaping of the router.
traffic_shaping:
  # Apply to all requests from clients to the router
  router:
    # Is the maximum size of the request body in MB, mib
    max_request_body_size: 20MB
#    max_header_bytes: "1MiB"
  all: # Rules are applied to all subgraph requests.
    # Subgraphs transport options
    request_timeout: 60s
    dial_timeout:  5s
    keep_alive_idle_timeout: 120s
    keep_alive_probe_interval: 30s
    retry:
      enabled: false

# Headers to be propagated to the backend
headers:
    all:
      request:
        - op: "propagate"
          matching: (?i)^x-.*
        - op: "propagate"
          matching: (?i)^am-.*
        - op: "propagate"
          matching: (?i)^as-.*


## accesslog
access_logs:
  enabled: true
  output:
    stdout:
      enabled: true
  buffer:
    enabled: false
    size: 256KB
    flush_interval: 10s
  router:
    fields:
      - key: "organization-id"
        value_from:
          request_header: "as-organization-id"
      - key: "am-trace-id"
        value_from:
          request_header: "x-cloud-trace-context"
      - key: "operationName"
        value_from:
          context_field: operation_name
      - key: "operationSha256"
        value_from:
          context_field: operation_sha256
      - key: "requestError"
        value_from:
          context_field: request_error
      - key: "responseErrorMessage"
        value_from:
          context_field: response_error_message
      - key: "serviceNames"
        value_from:
          context_field: operation_service_names
      - key: "operationHash"
        value_from:
          context_field: operation_hash
      - key: "errorCodes"
        value_from:
          context_field: graphql_error_codes
      - key: "operationType"
        value_from:
          context_field: operation_type
      - key: "persistentOperationSha256"
        value_from:
          context_field: persisted_operation_sha256
      - key: "errorServiceNames"
        value_from:
          context_field: graphql_error_service_names
      - key: "operationParsingTime"
        value_from:
          context_field: operation_parsing_time
      - key: "operationPlanningTime"
        value_from:
          context_field: operation_planning_time
      - key: "operationNormalizationTime"
        value_from:
          context_field: operation_normalization_time
      - key: "operationValidationTime"
        value_from:
          context_field: operation_validation_time
  subgraphs:
    enabled: true
    fields:
      - key: "organization-id"
        value_from:
          request_header: "as-organization-id"
      - key: "am-trace-id"
        value_from:
          request_header: "x-cloud-trace-context"
      - key: "operationName"
        value_from:
          context_field: operation_name
      - key: "operationSha256"
        value_from:
          context_field: operation_sha256
      - key: "operationHash"
        value_from:
          context_field: operation_hash
      - key: "operationType"
        value_from:
          context_field: operation_type
      - key: "persistentOperationSha256"
        value_from:
          context_field: persisted_operation_sha256
      - key: "operationParsingTime"
        value_from:
          context_field: operation_parsing_time
      - key: "operationPlanningTime"
        value_from:
          context_field: operation_planning_time
      - key: "operationNormalizationTime"
        value_from:
          context_field: operation_normalization_time
      - key: "operationValidationTime"
        value_from:
          context_field: operation_validation_time
      - key: "requestError"
        value_from:
          context_field: request_error
      - key: "responseErrorMessage"
        value_from:
          context_field: response_error_message
```

### Router execution config

```json

```

### Log output

```shell

```
