### ISSUE TITLE
Error not forward to client

### ISSUE THREAD

**Issue by Killian-Aidalinfo** [wundergraph/cosmo#1719]
### Component(s)

router

### Component version

0.192.1

### wgc version

0.75.11

### controlplane version

NoControlePane

### router version

0.192.1

### What happened?

It appears that you're encountering an issue where the Cosmo Router does not propagate detailed subgraph errors to the client as expected. Despite configuring subgraph_error_propagation with mode: pass-through and specifying allowed_extension_fields, the client consistently receives a generic error message: "Failed to fetch from Subgraph 'ms-authentification-habilitation'."

Configuration Details:

The router's configuration includes:

subgraph_error_propagation:
  mode: pass-through
  attach_service_name: true
  allowed_extension_fields:
    - "code"

Additionally, the subgraph is designed to throw errors with specific extensions, such as:

throw new GraphQLError("authentificationHabilitation.backend.session.expired", {
  extensions: {
    code: 'BAD_AUTHENTICATION',
  },
});

Observed Behavior:

Despite the above configurations, the client receives a generic error without the detailed information from the subgraph's extensions.

Expected Behavior:

With mode: pass-through, the router should relay the subgraph's detailed error messages and extensions directly to the client, allowing for more precise error handling and debugging.

Additional Context:

This behavior is unexpected based on the [Cosmo Router documentation on Subgraph Error Propagation](https://cosmo-docs.wundergraph.com/router/subgraph-error-propagation), which indicates that in pass-through mode, errors from subgraphs should be forwarded to the client without encapsulation.

A similar issue was previously reported in [Issue #740](https://github.com/wundergraph/cosmo/issues/740), where changes in error handling introduced breaking changes, leading to subgraph errors being wrapped or not propagated as before.

Request for Assistance:

Could you please provide guidance on how to ensure that the Cosmo Router propagates subgraph errors as intended in pass-through mode? Is there an additional configuration or update required to achieve the expected behavior?

Thank you for your support.

## Environment
OS: docker  node:20-slim

### Router configuration

```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/wundergraph/cosmo/main/router/pkg/config/config.schema.json
listen_addr: "0.0.0.0:4000"
introspection_enabled: true
json_log: true
shutdown_delay: 15s
grace_period: 20s
poll_interval: 10s
health_check_path: "/health"
readiness_check_path: "/health/ready"
liveness_check_path: "/health/live"
version: '1'
log_level: "debug"
headers:
  all:
    request:
      - op: "propagate"
        matching: ".*"

subgraph_error_propagation:
  mode: wrapped
  default_extension_code: DOWNSTREAM_SERVICE_ERROR
  omit_extensions: false
  propagate_status_codes: true
  omit_locations: true
  attach_service_name: true # Attach the service name to the error
  allowed_extension_fields: # Propagate additional fields from subgraphs
    - "code"
execution_config:    
  file:
    path: "/app/config/config.json"
```

### Router execution config

```json
Can expose this
```

### Log output

```shell
{"level":"info","time":1742890723920,"msg":"Serving GraphQL playground","hostname":"b2b2daf0ddf2","pid":1,"service":"@wundergraph/router","service_version":"0.192.1","url":"http://0.0.0.0:4000/"}
{"level":"debug","time":1742890723960,"msg":"Net poller is available","hostname":"b2b2daf0ddf2","pid":1,"service":"@wundergraph/router","service_version":"0.192.1"}
{"level":"info","time":1742890723965,"msg":"Static execution config provided. Polling and watching is disabled. Updating execution config is only possible by restarting the router","hostname":"b2b2daf0ddf2","pid":1,"service":"@wundergraph/router","service_version":"0.192.1"}
{"level":"info","time":1742890723965,"msg":"Server initialized and ready to serve requests","hostname":"b2b2daf0ddf2","pid":1,"service":"@wundergraph/router","service_version":"0.192.1","listen_addr":"0.0.0.0:4000","playground":true,"introspection":true,"config_version":"88076128-dda9-4e2d-ac57-f61b124dd55a"}
{"level":"debug","time":1742890833872,"msg":"Retrying request","hostname":"b2b2daf0ddf2","pid":1,"service":"@wundergraph/router","service_version":"0.192.1","retry":1,"url":"http://ms-authentification-habilitation:4000/graphql","sleep":0.607365954}
{"level":"debug","time":1742890833873,"msg":"Retrying request","hostname":"b2b2daf0ddf2","pid":1,"service":"@wundergraph/router","service_version":"0.192.1","retry":1,"url":"http://ms-authentification-habilitation:4000/graphql","sleep":1.011386571}
{"level":"debug","time":1742890833878,"msg":"Retrying request","hostname":"b2b2daf0ddf2","pid":1,"service":"@wundergraph/router","service_version":"0.192.1","retry":1,"url":"http://ms-authentification-habilitation:4000/graphql","sleep":2.052460537}
{"level":"debug","time":1742890833879,"msg":"Retrying request","hostname":"b2b2daf0ddf2","pid":1,"service":"@wundergraph/router","service_version":"0.192.1","retry":1,"url":"http://ms-annuaire:4000/graphql","sleep":0.838220619}
{"level":"info","time":1742890834482,"msg":"/graphql","hostname":"b2b2daf0ddf2","pid":1,"log_type":"request","method":"POST","path":"/graphql","query":"","ip":"[REDACTED]","user_agent":"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Mobile Safari/537.36","config_version":"88076128-dda9-4e2d-ac57-f61b124dd55a","trace_id":"8f360d1ff3d95cb67a5d8820e6265ed4","latency":0.615085998,"status":200,"request_id":"b2b2daf0ddf2/qShn6UrTCA-000003"}
{"level":"info","time":1742890834721,"msg":"/graphql","hostname":"b2b2daf0ddf2","pid":1,"log_type":"request","method":"POST","path":"/graphql","query":"","ip":"[REDACTED]","user_agent":"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Mobile Safari/537.36","config_version":"88076128-dda9-4e2d-ac57-f61b124dd55a","trace_id":"9ce317b1226ffe5ac7566a22abcb620f","latency":0.847362561,"status":200,"request_id":"b2b2daf0ddf2/qShn6UrTCA-000006"}
{"level":"info","time":1742890834886,"msg":"/graphql","hostname":"b2b2daf0ddf2","pid":1,"log_type":"request","method":"POST","path":"/graphql","query":"","ip":"[REDACTED]","user_agent":"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Mobile Safari/537.36","config_version":"88076128-dda9-4e2d-ac57-f61b124dd55a","trace_id":"45dc4e224bef38697aaba77a211634c7","latency":1.018421107,"status":200,"request_id":"b2b2daf0ddf2/qShn6UrTCA-000004"}
{"level":"info","time":1742890835934,"msg":"/graphql","hostname":"b2b2daf0ddf2","pid":1,"log_type":"request","method":"POST","path":"/graphql","query":"","ip":"[REDACTED]","user_agent":"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Mobile Safari/537.36","config_version":"88076128-dda9-4e2d-ac57-f61b124dd55a","trace_id":"383f102d197d0ccff4fabc387c71af7d","latency":2.060918266,"status":200,"request_id":"b2b2daf0ddf2/qShn6UrTCA-000005"}
```

**Comment by Aenimus** [comment]
Hi @Killian-Aidalinfo,

How are you confirming that request is actually reaching the subgraph?

**Comment by Killian-Aidalinfo** [comment]
Hi @Aenimus 

Yes, it reaches the subgraph, and the subgraph executes the GraphQL Error code with the customized code.

**Comment by Aenimus** [comment]
Hi @Killian-Aidalinfo,

How are you running the router? Are you able to confirm that it is reacting to your `config.yaml`? For instance, if you change the the listen address to port `4123` does that happen as expected?

**Comment by Aenimus** [comment]
Hi @Killian-Aidalinfo,

It looks to us that you intended the `mode` to be `pass-through`, but your configuration states `wrapped`. Please try changing it to `pass-through` and update us.

**Comment by Killian-Aidalinfo** [comment]
@Aenimus yes, config.yaml is supported by the router, if I change the listening port it works 

I tested the pass-through mode too before making the exit but it doesn't work, nothing changes at the error level.


Router dockerfile :

```
# Utilise une image de base légère avec Node.js et wget
FROM node:20-slim

# Définir le répertoire de travail
WORKDIR /app

# Installer wget et les dépendances nécessaires
RUN apt-get update && \
    apt-get install -y wget curl && \
    rm -rf /var/lib/apt/lists/*

# Télécharger et extraire le routeur Cosmo
# RUN wget https://github.com/wundergraph/cosmo/releases/download/router%400.192.1/router-router@0.192.1-linux-amd64.tar.gz && \
#     tar -xzf router-router@0.192.1-linux-amd64.tar.gz && \
#     rm router-router@0.192.1-linux-amd64.tar.gz

# # Rendre le binaire du routeur exécutable

# Installer wgc globalement
RUN npm install -g wgc@latest
RUN npx wgc router download-binary
RUN chmod +x /app/router/router
# Copier le script d'entrée
COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

# Exposer le port sur lequel le routeur écoutera
EXPOSE 4000

# Définir le script comme point d'entrée
ENTRYPOINT ["/app/entrypoint.sh"]
```


Entreypoint.sh :

```bash
#!/bin/bash

set -e

# Vérifier si la variable d'environnement est définie
if [ -z "$MS_BACKEND_GATEWAY_MICROSERVICES" ]; then
  echo "La variable d'environnement MS_BACKEND_GATEWAY_MICROSERVICES n'est pas définie."
  exit 1
fi

mkdir -p /app/config


rm -rf /app/config/config.json

echo "Tous les services sont disponibles. Fichier supergraph.yaml généré."
npx wgc router compose --input "/tmp/graph.yaml" --out /app/config/config.json
# Lancer le routeur avec la configuration générée
exec /app/router/router --config "/config.yaml"
```

Config.yaml :

```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/wundergraph/cosmo/main/router/pkg/config/config.schema.json
listen_addr: "0.0.0.0:4000"
introspection_enabled: true
json_log: true
shutdown_delay: 15s
grace_period: 20s
poll_interval: 10s
health_check_path: "/health"
readiness_check_path: "/health/ready"
liveness_check_path: "/health/live"
version: '1'
log_level: "debug"
headers:
  all:
    request:
      - op: "propagate"
        matching: ".*"

subgraph_error_propagation:
  mode: pass-through
  attach_service_name: true
  allowed_extension_fields:
    - "code"
    
execution_config:    
  file:
    path: "/app/config/config.json"
```

Docker compose with microservice and router :

```yaml

  cosmo-router:
    build:
      context: ./wgraph
      dockerfile: Dockerfile
    volumes:
        - ./wgraph/graph.yaml:/tmp/graph.yaml
        - ./wgraph/config.yaml:/config.yaml
    env_file:
      - .env
    ports:
      - 8081:4000
```

The microservice in question returns the 2 errors and goes through both loops:

```javascript

        if (compteurTryToken >= 3) {
          compteurTryToken = 0;
          throw new GraphQLError("Boucle token", {
            extensions: {
              code: 'BAD_AUTHENTICATION',
            },
          });
        }

        compteurTryToken++;

        throw new GraphQLError("authentificationHabilitation.backend.session.expired", {
          extensions: {
            code: 'BAD_AUTHENTICATION',
          },
        });
```

And on the client I've added these console logs 

```
    const errorLink = onError(({ networkError, operation, forward, graphQLErrors }) => {
      console.log("GraphQL Error", graphQLErrors)
      console.log("network Error", networkError)
```


Result :

```
GraphQL Error [{…}]0: message: "Failed to fetch from Subgraph 'ms-authentification-habilitation'."[[Prototype]]: Objectlength: 1[[Prototype]]: Array(0)
apollo.js:43 network Error undefined
```

**Comment by Aenimus** [comment]
Hi @Killian-Aidalinfo,

Please share the raw JSON response returned by the subgraph (before it reaches the router), and the ART (Advanced Request Tracing) of the response from the router. The ART is the `trace` property that can be found withing the `extensions` property in the router response JSON.

**Comment by Aenimus** [comment]
Hi @Killian-Aidalinfo,

As a first step, please can you try with the latest router version, then report back? There was a recent update that might "fix" the issue.

**Comment by buger** [comment]
Check this research, maybe it can point you to the right direction

----

# Potential Bug in Cosmo Router's HTTP Request Handling

After analyzing the code, I've identified a potential bug that could cause the "ContentLength=100 with Body length 0" error you're experiencing.

## The Bug

The issue likely occurs in the request processing pipeline, specifically in how request bodies are handled before being sent to subgraphs. There are two main areas where this could happen:

1. **Compression Middleware**: In `router/internal/middleware/compression.go`, when a compressed request body is decompressed, the middleware replaces the original body with a decompressed reader but **does not update the Content-Length header**. This creates a mismatch between the declared content length and actual body size.

```go
// In HandleCompression middleware
switch strings.TrimSpace(encodings[0]) {
case "gzip":
    gzr, err := gzip.NewReader(r.Body)
    if err != nil {
        logger.Error("failed to create gzip reader", zap.Error(err))
        http.Error(w, "invalid gzip payload", http.StatusUnprocessableEntity)
        return
    }
    
    defer func() {
        if err := gzr.Close(); err != nil {
            logger.Error("failed to close gzip reader", zap.Error(err))
        }
    }()
    
    r.Body = gzr  // Body is replaced but Content-Length remains unchanged
    // No code to update Content-Length header
}
```

2. **Body Consumption**: In various places throughout the codebase, the request body might be read but not properly restored with the correct Content-Length.

## How to Fix It

Here are actionable steps to resolve this issue:

1. **Disable compression in your client requests**:
   - Add `'Accept-Encoding': 'identity'` to your client request headers to prevent compression.

2. **Add Content-Length header explicitly in your client**:
   - Calculate and set the Content-Length header manually:
   ```javascript
   const body = JSON.stringify({query: "..."});
   fetch('http://your-router/graphql', {
     method: 'POST',
     headers: {
       'Content-Type': 'application/json',
       'Content-Length': Buffer.byteLength(body).toString()
     },
     body: body
   });
   ```

3. **Modify your Docker setup**:
   - If you're using a reverse proxy (like Nginx), check if it's modifying the request before it reaches the router.
   - Ensure your Docker networking is properly configured with:
   ```
   docker network inspect <your_network>
   ```

4. **Update router configuration**:
   - Set explicit timeouts for HTTP connections:
   ```yaml
   subgraph_transport_options:
     timeout: 30  # seconds
     disable_compression: true
   ```

5. **Check for middleware interference**:
   - If you've added custom middleware to your setup, ensure it's not consuming the request body without restoring it properly.

This issue is likely a bug in how the router handles request bodies in certain scenarios, particularly with compression or when the body is read multiple times. By implementing these steps, you should be able to work around the issue until a proper fix is released.
