### ISSUE TITLE
Failure to execute query in persisted queries safelist

### ISSUE THREAD

**Issue by george-ivanov** [wundergraph/cosmo#1824]
### Component(s)

router

### Component version

0.203.0

### wgc version

0.76.1

### controlplane version

n/a - router only setup

### router version

0.203.0

## Description
In a router only (no cosmo cloud) setup when using persisted queries and safelist is on.
```
persisted_operations:
  log_unknown: true
  safelist:
    enabled: true
  storage:
    provider_id: "s3-provider"
    object_prefix: "persisted_ops"
```

## Steps to Reproduce
1) Execute the actual query - works fine
2) Execute the query via its hash - works fine
3) Execute the actual query once more - fails with "document doesn't contain any executable operation"
4) Execute the actual query once more - fails with a server error

Note: Executing the query via its hash continues to work

## Expected Result
Should return query results

## Actual Result
`18:12:04 PM ERROR requestlogger/requestlogger.go:157 [Recovery from panic] {"hostname": "C4QAAAAAA", "pid": 75601, "log_type": "request", "method": "POST", "path": "/graphql", "query": "", "ip": "[REDACTED]", "user_agent": "PostmanRuntime/7.43.4", "config_version": "fbe7ac51-4f1a-4ddd-97b8-06790d554851", "trace_id": "4cf17a60bf3c76f292763f0fcb3ea3f7", "status": 500, "latency": 0.000230167, "error": "runtime error: index out of range [0] with length 0", "request_id": "C4QAAAAAA/bGE7UZCsqb-000015"}
github.com/wundergraph/cosmo/router/internal/requestlogger.(*handler).ServeHTTP.func1
	github.com/wundergraph/cosmo/router/internal/requestlogger/requestlogger.go:157
runtime.gopanic
	runtime/panic.go:792
runtime.goPanicIndex
	runtime/panic.go:115
github.com/wundergraph/cosmo/router/core.(*OperationKit).NormalizeVariables
	github.com/wundergraph/cosmo/router/core/operation_processor.go:781
github.com/wundergraph/cosmo/router/core.(*PreHandler).handleOperation
	github.com/wundergraph/cosmo/router/core/graphql_prehandler.go:714
github.com/wundergraph/cosmo/router/core.(*PreHandler).Handler-fm.(*PreHandler).Handler.func1
	github.com/wundergraph/cosmo/router/core/graphql_prehandler.go:398
net/http.HandlerFunc.ServeHTTP
	net/http/server.go:2294
github.com/wundergraph/cosmo/router/core.NewWebsocketMiddleware.func1.1
	github.com/wundergraph/cosmo/router/core/websocket.go:146
net/http.HandlerFunc.ServeHTTP
	net/http/server.go:2294
github.com/wundergraph/cosmo/router/internal/requestlogger.(*handler).ServeHTTP
	github.com/wundergraph/cosmo/router/internal/requestlogger/requestlogger.go:168
github.com/wundergraph/cosmo/router/core.(*graphServer).buildGraphMux.func4.1
	github.com/wundergraph/cosmo/router/core/graph_server.go:878
net/http.HandlerFunc.ServeHTTP
	net/http/server.go:2294
github.com/wundergraph/cosmo/router/core.(*graphServer).buildGraphMux.func3.1
	github.com/wundergraph/cosmo/router/core/graph_server.go:853
net/http.HandlerFunc.ServeHTTP
	net/http/server.go:2294
github.com/wundergraph/cosmo/router/internal/recoveryhandler.(*handler).ServeHTTP
	github.com/wundergraph/cosmo/router/internal/recoveryhandler/recovery.go:59
github.com/wundergraph/cosmo/router/core.(*graphServer).buildGraphMux.func1.1
	github.com/wundergraph/cosmo/router/core/graph_server.go:795
net/http.HandlerFunc.ServeHTTP
	net/http/server.go:2294
github.com/go-chi/chi/v5.(*Mux).ServeHTTP
	github.com/go-chi/chi/v5@v5.2.1/mux.go:73
net/http.HandlerFunc.ServeHTTP
	net/http/server.go:2294
github.com/wundergraph/cosmo/router/core.newGraphServer.func2.CookieWhitelist.2.1
	github.com/wundergraph/cosmo/router/internal/middleware/cookie_filter.go:12
net/http.HandlerFunc.ServeHTTP
	net/http/server.go:2294
github.com/klauspost/compress/gzhttp.NewWrapper.func1.1
	github.com/klauspost/compress@v1.17.9/gzhttp/compress.go:495
net/http.HandlerFunc.ServeHTTP
	net/http/server.go:2294
github.com/go-chi/chi/v5.(*ChainHandler).ServeHTTP
	github.com/go-chi/chi/v5@v5.2.1/chain.go:31
github.com/go-chi/chi/v5.(*Mux).routeHTTP
	github.com/go-chi/chi/v5@v5.2.1/mux.go:480
net/http.HandlerFunc.ServeHTTP
	net/http/server.go:2294
github.com/wundergraph/cosmo/router/pkg/trace.(*Middleware).Handler.func1
	github.com/wundergraph/cosmo/router/pkg/trace/middleware.go:54
net/http.HandlerFunc.ServeHTTP
	net/http/server.go:2294
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*middleware).serveHTTP
	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.46.1/handler.go:229
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.NewMiddleware.func1.1
	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.46.1/handler.go:81
net/http.HandlerFunc.ServeHTTP
	net/http/server.go:2294
github.com/wundergraph/cosmo/router/pkg/cors.(*cors).ServeHTTP
	github.com/wundergraph/cosmo/router/pkg/cors/config.go:67
github.com/go-chi/chi/v5/middleware.RealIP.func1
	github.com/go-chi/chi/v5@v5.2.1/middleware/realip.go:36
net/http.HandlerFunc.ServeHTTP
	net/http/server.go:2294
github.com/go-chi/chi/v5/middleware.RequestID.func1
	github.com/go-chi/chi/v5@v5.2.1/middleware/request_id.go:76
net/http.HandlerFunc.ServeHTTP
	net/http/server.go:2294
github.com/wundergraph/cosmo/router/core.newGraphServer.HandleCompression.func8.1
	github.com/wundergraph/cosmo/router/internal/middleware/compression.go:52
net/http.HandlerFunc.ServeHTTP
	net/http/server.go:2294
github.com/wundergraph/cosmo/router/core.newGraphServer.RequestSize.func7.1
	github.com/wundergraph/cosmo/router/internal/middleware/request_size.go:14
net/http.HandlerFunc.ServeHTTP
	net/http/server.go:2294
github.com/wundergraph/cosmo/router/internal/recoveryhandler.(*handler).ServeHTTP
	github.com/wundergraph/cosmo/router/internal/recoveryhandler/recovery.go:59
github.com/go-chi/chi/v5.(*Mux).ServeHTTP
	github.com/go-chi/chi/v5@v5.2.1/mux.go:90
github.com/wundergraph/cosmo/router/core.newServer.func1
	github.com/wundergraph/cosmo/router/core/http_server.go:77
net/http.HandlerFunc.ServeHTTP
	net/http/server.go:2294
net/http.serverHandler.ServeHTTP
	net/http/server.go:3301
net/http.(*conn).serve
	net/http/server.go:2102`

## Environment
OS: MacOS 15.4.1

### Router configuration

```yaml
version: "1"

headers:
  all: # Header rules for all subgraph requests.
    request:
      - op: "propagate"
        named: apiKey
      - op: "propagate"
        named: Authorization        

dev_mode: true

execution_config: 
  file:
    # Path to the previous generated file
    path: "router.json" # or EXECUTION_CONFIG_FILE_PATH
    watch: true # EXECUTION_CONFIG_FILE_WATCH

storage_providers:
  s3:
    - id: "s3-provider"
      endpoint: "s3.amazonaws.com"
      access_key: "ATPP"
      secret_key: "c5V"
      bucket: "s3-test"
      region: "eu-west-1"
      secure: true
  # file_system:
  #   - id: "fs-provider"
  #     path: "/Users/georivan/Documents/Cosmo/"

# security:
#   block_non_persisted_operations:
#     enabled: true

persisted_operations:
  log_unknown: true
  safelist:
    enabled: false
  storage:
    provider_id: "s3-provider"
    object_prefix: "persisted_ops"
```

### Router execution config

```json

```

### Log output

```shell

```
