### ISSUE TITLE
Support for MCP endpoint in router helm chart

### ISSUE THREAD

**Issue by darkms** [wundergraph/cosmo#1861]
### Component(s)

helm

### Is your feature request related to a problem? Please describe.

Hi everyone,
Currently the [router helm chart](https://github.com/wundergraph/cosmo/tree/main/helm/cosmo/charts/router) only supports ports for primary router HTTP and Prometheus metrics endpoints, but the new MCP server endpoint does not seem to be supported in Helm chart yet.

### Describe the solution you'd like

I would like to be able to enable MCP server in a similar way to how Prometheus endpoint works now.
From my brief study it seems changes would need to be made to [service](https://github.com/wundergraph/cosmo/blob/main/helm/cosmo/charts/router/templates/service.yaml) (conditionally add new port), [deployment](https://github.com/wundergraph/cosmo/blob/main/helm/cosmo/charts/router/templates/deployment.yaml) (conditionally add new port), [values](https://github.com/wundergraph/cosmo/blob/main/helm/cosmo/charts/router/values.yaml) (add new section for MCP server configuration), though there might be more places I might be missing.

For values file I believe the structure could look like:
```
configuration:
  ... # all existing code in this section

  # Use this section to disable/enable and configure MCP server.
  mcp:
    # -- Enables MCP server support. Default is false.
    enabled: true
    # -- The port where MCP server is exposed. Default is port 5025.
    port: 5025
```
