### ISSUE TITLE
Proxy headers from Subgraphs to client

### ISSUE THREAD

**Issue by vasily-polonsky** [wundergraph/cosmo#332]
### Is your feature request related to a problem? Please describe.

I want to pass headers from subgraph back to client, but only found a way to pass from router to subgraph. Would be cool to have this in proxy settings as well. Found a way to create a custom module to modify headers using custom modules. Would be nice to have this feature as it is much easier, you don't have to build a router and you need only configure yaml file.

### Describe the solution you'd like

```
headers:
  all: (subgraphs)
    response:
```

**Comment by StarpTech** [comment]
Hi @vasily-polonsky, thank you for sharing your experience with us. I like the proposal. It's not on the Roadmap yet but will discuss it internally. How was the experience to build a custom module? 

Do you reach out as a company or individual? Thank you.

**Comment by jensneuse** [comment]
If 2 subgraphs return the same Header which should be "backwarded", and they return different values, what should be the desired behavior? Last write wins? As in, last returned value from a subgraph gets returned?

**Comment by vasily-polonsky** [comment]
Hi @StarpTech 
I reach out as an individual. I have only had positive experiences, thanks to examples and documents.

**Comment by vasily-polonsky** [comment]
Hi @jensneuse 
I think the best way is to follow the same approach as its already done for proxying request header https://cosmo-docs.wundergraph.com/router/proxy-capabilities
In case the user has multiple subgraphs that return the same header, he can solve this problem by specifying a concrete graph. 

```
headers:
  all: # Header rules for all subgraph requests.
    reponse:
      - op: "propagate"            # Forward a client header
        named: X-Test-Header       # Exact match (Use the canonicalized version)
       
  subgraphs:
    specific-subgraph: # Will only affect this subgraph
      request:  
        - op: "propagate"
          named: Specific-Header
```

 In my case, I only need to propagate the header from a specific subgraph to the client.
