### ISSUE TITLE
Router - Forward generated Request-Id to subgraph

### ISSUE THREAD

**Issue by oxyno-zeta** [wundergraph/cosmo#534]
### Component(s)

router

### Is your feature request related to a problem? Please describe.

As an operation team member, I would like to forward the generated request-id (generated by chi middleware if request doesn't have it) to subgraph.

### Describe the solution you'd like

In configuration and using the "Header manipulation" feature, I would like to be able to forward X-Request-Id (even if it is generated by router backend) to subgraph backends.

Something like this:

```yaml
headers:
  all: # Header rules for all origin requests.
    request:
      - op: "propagate"
        named: X-Request-Id
```
