### ISSUE TITLE
Allow to rename client headers on propagate to subgraphs

### ISSUE THREAD

**Issue by StarpTech** [wundergraph/cosmo#604]
### Is your feature request related to a problem? Please describe.

As a User, I'd like rename client headers and forward them to subgraphs. We already provide a feature to forward headers (see [here](https://cosmo-docs.wundergraph.com/router/proxy-capabilities#supported-header-rules)). Rewriting headers should be configured similar.

### Describe the solution you'd like

Rewriting headers should be configured in the following way.

```yaml
headers:
  all:
    request:
      - op: "propagate" 
        named: "X-User-Id"
        rename: "account-id" # new field, renames the header's key to the provided value
```
The config will rename an incoming client header `X-User-Id` to `User-ID`. `named` and and `matching` must still work as documented.

**Requirements:**

- No CGO.
- The new router configuration needs to be validated through our JSON schema definition.
- Functionality must be provided in separate Go modules with unit tests and integration test. See [test suite](https://github.com/wundergraph/cosmo/tree/main/router-tests).

### Additional context

Original issue: https://github.com/wundergraph/cosmo/issues/503
