### ISSUE TITLE
Headers and extensions are not being propagated to subgraphs

### ISSUE THREAD

**Issue by ricardomcg** [wundergraph/cosmo#625]
### Component(s)

router

### Component version

0.71.2

### wgc version

latest

### controlplane version

0.73.2

### router version

0.71.2

### What happened?

According to the documentation:

> Header forwarding
Headers in subscriptions can be forwarded through the router to the subgraphs using the proxy capabilities for the router.

We have configured header propagation on the config file, it works great on queries but it doesn't on subscriptions, when debugging the subgraph the headers that were supposed to be propagated are not in the request that reached the subgraph.

I also tried using extensions but I get the same result.

### Environment information

Running on a GKE cluster, using helm deployment

### Router configuration

```yaml
# Default values for router.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: wundergraph/cosmo/router
  registry: ghcr.io
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart appVersion.
  version: "latest"

service:
  type: ClusterIP
  port: 3002

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "service-cosmo-qa"

global:
  router:
    enabled: true

  minio:
    enabled: true

  cdn:
    enabled: true
    s3StorageUrl: 'http://minio:changeme@cosmo-minio:9000/cosmo'

  helmTests:
    enabled: false
  seed:
    enabled: false

  studio:
    enabled: false

  clickhouse:
    enabled: false

  postgresql:
    enabled: false

  redis:
    enabled: false

  controlplane:
    enabled: false

  otelcollector:
    enabled: false

  graphqlmetrics:
    enabled: false

  keycloak:
    enabled: false

# Overall Ingress for the Cosmo Platform
ingress:
  enabled: false
  
cdn:
  configuration:
    # This must match the value used in controlplane.configuration.s3StorageUrl
    s3StorageUrl: 'http://minio:changeme@cosmo-qa-minio:9000/cosmo'

router:
  extraEnvVars:
    - name: CDN_URL
      value: "http://cosmo-router-qa-cdn:8787"

    - name: PLAYGROUND_PATH
      value: "/cosmo/v1/"

    - name: GRAPHQL_PATH
      value: "/cosmo/v1/graphql"

  commonConfiguration: |-
    version: "1"
    log_level: "warning"

    headers:
      all: # Header rules for all subgraph requests.
        request:
          - op: "propagate"            # Forward a client header
            named: Authorization       # Exact match (Use the canonicalized version)
          - op: "propagate"            # Forward a client header
            named: session-id       # Exact match (Use the canonicalized version)
    
    engine:
      debug:
        report_websocket_connections: true

  configuration:
    graphApiToken: "SECRET_TOKEN"
    # -- The execution config file to statically configure the router. If set, polling of the config is disabled.
    # -- If your config exceeds 1MB (Kubernetes limit), you have to mount it as a file and set the path in routerConfigPath instead
    executionConfig: ""
    # -- The log level of the router. Default to info if not set.
    logLevel: "debug"
    # -- The URL of the Cosmo Controlplane. Should be internal to the cluster. Default to cloud if not set.
    controlplaneUrl: 'https://cosmocontrolplane.mydomain.com'
    # -- The URL of the Cosmo GraphQL OTEL Collector. Should be internal to the cluster.
    # otelCollectorUrl: 'http://cosmo-qa-otelcollector:4318'
    otelCollectorUrl: 'https://cosmootel.mydomain.com'
    # -- The URL of the Cosmo GraphQL Metrics Collector. Should be internal to the cluster.
    # graphqlMetricsCollectorUrl: 'http://cosmo-qa-graphqlmetrics:4005'
    graphqlMetricsCollectorUrl: 'https://cosmographql.mydomain.com'
    # # -- The URL of the Cosmo CDN. Should be internal to the cluster.
    # cdnUrl: 'http://cosmo-qa-cdn:8787'
    cdnUrl: 'http://cosmo-router-qa-cdn:8787'
    # -- The path to the router execution config file. Before, you have to mount the file as a volume and set the path here.
    # -- A possible to solution could be to use an init container to download the file from a CDN. If set, polling of the config is disabled.
    routerConfigPath: ""
```

### Additional context

We have router + CDN in one cluster, and studio, controlplane, etc in another.

Everything can connect to itself as that has been tested, and all pods are running fine.
