### ISSUE TITLE
Add annotations value for pod in k8s jobs

### ISSUE THREAD

**Issue by PeteMac88** [wundergraph/cosmo#651]
### Component(s)

controlplane

### Is your feature request related to a problem? Please describe.

Add annotations value for pod in k8s jobs

### Describe the solution you'd like

I added a PR see https://github.com/wundergraph/cosmo/pull/650

**Comment by Aenimus** [comment]
Hi,

Thank you for your contribution! We will take a look in due course.

Thank you also for your patience!

**Comment by PeteMac88** [comment]
@Aenimus Any news here? I can open a PR if you want?

**Comment by StarpTech** [comment]
Hi @PeteMac88 we added support for [labels](https://github.com/wundergraph/cosmo/blob/main/helm/cosmo/charts/controlplane/values.yaml#L245-L287) but annotations are missing. Feel free to create a PR that extends it in the same way.

```yaml
additionalJobAnnotations: {}

jobs:
  # -- Used to deactivate an organization with a reason and schedule deletion
  deactivateOrganization:
    additionalAnnotations: {}
```
