### ISSUE TITLE
Breaking change in error handling

### ISSUE THREAD

**Issue by oxyno-zeta** [wundergraph/cosmo#740]
### Component(s)

router

### Component version

0.82.1

### wgc version

0.51.2

### controlplane version

n/a

### router version

0.82.1

## Description
This pull request #647 have created a breaking change in error handling through the router.

Here is the reproduction case:
https://github.com/wundergraph/cosmo/blob/700d36894464ab14a52e003952a10599c97f5e7a/router-tests/integration_test.go#L830

Before, at least in 0.68.0, it was forwading the subgraph error without any modification/wrapping. This is introducing a breaking change and forced us to rollback as you can imagine :) . Applications was looking for error extensions in some cases and cannot find them and so can't manage the error.

I'm speaking about a breaking change since there isn't any way to have the previous behavior.

## Expected Result

Answer with subgraph error without any wrapping:
```json
{
  "errors": [
    {
      "message": "Unauthorized",
      "extensions": { "code": "UNAUTHORIZED" }
    }
  ],
  "statusCode": 403, // => With the status code feature
  "data": {
    "employees": [
      {
        "id": 1,
        "details": { "forename": "Jens", "surname": "Neuse" },
        "notes": null
      }
    ]
  }
}
```

Note: I'm using the unit test data as example. I'm just cleaning a bit the data part as it isn't the interesting point here

## Actual Result

```json
{
  "errors": [
    {
      "message": "Failed to fetch from Subgraph '3' at path 'query.employees.@'.",
      "extensions": {
        "errors": [
          {
            "message": "Unauthorized",
            "extensions": { "code": "UNAUTHORIZED" }
          }
        ],
        "statusCode": 403
      }
    }
  ],
  "data": {
    "employees": [
      {
        "id": 1,
        "details": { "forename": "Jens", "surname": "Neuse" },
        "notes": null
      }
    ]
  }
}
```
Note: I'm using the unit test data as example. I'm just cleaning a bit the data part as it isn't the interesting point here

## Environment
Container image: ghcr.io/wundergraph/cosmo/router:0.82.1

### Router configuration

```yaml
subgraph_error_propagation:
  enabled: true
json_log: true
log_level: "info"
listen_addr: "0.0.0.0:3003"
playground_path: /playground
introspection_enabled: true
# Path to the previous generated file
router_config_path: /execution/execution-config.json
graph:
  # Result of `wgc router token create`. Can be omitted for local testing.
  token: ""
# Header manipulation
# See "https://cosmo-docs.wundergraph.com/router/proxy-capabilities" for more information
headers:
  all: # Header rules for all origin requests.
    request:
      - op: "propagate"
        named: Authorization
      - op: "propagate"
        named: X-Request-Id
      - op: "propagate"
        named: X-Correlation-Id

traffic_shaping:
  # Apply to all requests from clients to the router
  router:
    # Is the maximum size of the request body in MB, mib
    max_request_body_size: 5MB
  all: # Rules are applied to all subgraph requests.
    # Subgraphs transport options
    request_timeout: 60s
    dial_timeout: 30s
    tls_handshake_timeout: 0s
    response_header_timeout: 0s
    expect_continue_timeout: 0s
    keep_alive_idle_timeout: 0s
    keep_alive_probe_interval: 30s
    # Retry
    retry: # Rule is only applied to GraphQL operations of type "query"
      enabled: true
      algorithm: "backoff_jitter"
      max_attempts: 5
      interval: 3s
      max_duration: 10s

engine:
  enable_single_flight: true
  enable_request_tracing: true
  enable_execution_plan_cache_response_header: false
  max_concurrent_resolvers: 1024
  enable_websocket_epoll_kqueue: false
  epoll_kqueue_poll_timeout: "1s"
  epoll_kqueue_conn_buffer_size: 128
  websocket_read_timeout: "1s"
  execution_plan_cache_size: 10000
  debug:
    report_websocket_connections: false
    report_memory_usage: false
```
