### ISSUE TITLE
Memory leak during configuration update

### ISSUE THREAD

**Issue by flymedllva** [wundergraph/cosmo#756]
### Component(s)

router

### Component version

-

### wgc version

-

### controlplane version

-

### router version

v0.82.1

## Description

When updating the router configuration using `r.updateServerAndStart`, memory consumption increases.

Enough N times, make the schema puller download and apply a new schema, each time a new schema is applied (they must be different) the memory consumption of the application increases.

This is especially noticeable on large schematics larger than 20 mb.

## Steps to Reproduce

I made an example frequently updating the schema, after a few minutes of router operation the memory consumption increases even on a small schema

In order to reproduce, clone the repository and start the router

https://github.com/flymedllva/cosmo-memory-leak-during-configuration-update

```bash
cd router && make dev
```

Commit necessary to reproduce the problem: https://github.com/flymedllva/cosmo-memory-leak-during-configuration-update/commit/880955ebc9e0435e3d9c2dfed7faa3dfb57f56c9

### Environment information

OS: 14.4 (23E214)
Package Manager: npm
Compiler(if manually compiled): go version go1.22.1 darwin/arm64

### Router configuration

```
version: "1"

# General router options
graph:
  name: "production"
  token: ""

log_level: "info"
listen_addr: "localhost:3002"
playground_enabled: true
introspection_enabled: true
json_log: true
shutdown_delay: 15s
grace_period: 20s
poll_interval: 10s
health_check_path: "/health"
readiness_check_path: "/health/ready"
liveness_check_path: "/health/live"
router_config_path: "config.json"

cors:
  allow_origins: ["*"]
  allow_methods:
    - HEAD
    - GET
    - POST
  allow_headers:
    - Origin
    - Content-Length
    - Content-Type
  allow_credentials: true
  max_age_minutes: 5m

# Config for custom modules   
# See "https://cosmo-docs.wundergraph.com/router/custom-modules" for more information   
modules:
  myModule:
    # Arbitrary values, unmarshalled by the module
    value: 1

```

### Additional context

<img width="251" alt="Screenshot 2024-04-26 at 00 53 45" src="https://github.com/wundergraph/cosmo/assets/33265875/802edf50-a192-417b-bbda-d313f037e70b">
