### ISSUE TITLE
headers propagation

### ISSUE THREAD

**Issue by oerhahon** [wundergraph/cosmo#81]
For some reason, I can't propagate headers to my subgraph. I specifically want to propagate the Authorization header to the subgraph

```
headers:
  all:
    request:
      - op: "propagate"
        named: Authorization
      - op: "propagate"
        matching:  .*
```

From the documentation, the above code should work. 

My router is currently deployed using a Dockerfile:

```
FROM ghcr.io/wundergraph/cosmo/router:latest

WORKDIR /

COPY config.yaml ./

EXPOSE 3002
```
