### ISSUE TITLE
Add metrics container port to kubernetes Deployment and Service helm chart of Router

### ISSUE THREAD

**Issue by miguel-cardoso-mindera** [wundergraph/cosmo#826]
### Component(s)

router

### Is your feature request related to a problem? Please describe.

We currently have an issue while scraping our cosmo router instance, as by default prometheus listens to the 8088 port, however this port is not defined neither in the containerPort spec of the Deployment neither in the Service ports spec

### Describe the solution you'd like

Add both entries to their respective files, using a new variable called metricsPort or something like that here:

```
service:
  type: ClusterIP
  port: 3002
  metricsPort: 8088
```

and in the service for example:
```
apiVersion: v1
kind: Service
metadata:
  name: {{ include "router.fullname" . }}
  annotations:
  {{- with .Values.serviceAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "router.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "router.selectorLabels" . | nindent 4 }}
```

Do the same for the deployment containerPorts. Also maybe add by default PROMETHEUS_LISTEN_ADDR env var with the port specified

### Additional context

I'll happily open a PR if this is accepted, otherwise I would like to explore alternatives because it is quite bad currently the way we have manually edit the deployment and service resources on our cluster

**Comment by StarpTech** [comment]
Hi @miguel-cardoso-mindera, Thank you for opening this issue. We're aware of that limitation and will address this soon. We would be happy to review a PR.

**Comment by miguel-cardoso-mindera** [comment]
hey @StarpTech I opened the initial PR here: https://github.com/wundergraph/cosmo/pull/828

I'm unsure how many safety checks we want to add to this, for example, if we want to gate this behind some sort of "prometheus.enabled" gate, if we want to auto configure the prometheus listen address port with this variable etc

Just wanted to get the PR out there, I'm open to feedback and work on it further if needed.

Thanks in advance

**Comment by StarpTech** [comment]
Hi @miguel-cardoso-mindera I like your second approach. Instead of defining the port in the service section, we can create a `prometheus` section and pass those values as environment variables to the deployment.

```yaml
configuration:
  prometheus:
    enabled: true # PROMETHEUS_ENABLED
    port: 127.0.0.1:8088 # PROMETHEUS_LISTEN_ADDR
```

**Comment by miguel-cardoso-mindera** [comment]
Thanks for the suggestions, I've updated the PR and added the following block:
```
    prometheus:
      enabled: true
      port: 8088
      path: "/metrics"
```

I feel like having only the port instead of the full listen address is more advantageous as I can use it as is on the containerPort and service port specs. I'm also not sure if the address will ever be different than 127.0.0.1?
