### ISSUE TITLE
High memory utilization after router upgrade to 0.91.0

### ISSUE THREAD

**Issue by PeteMac88** [wundergraph/cosmo#854]
### Component(s)

router

### Component version

0.91.0

### wgc version

latest

### controlplane version

latest

### router version

0.91.0

### What happened?

After upgrading from router version 0.84.4 we observe much higher memory utilization of the router instances. Initially after the upgrade all instances were OOMKilled because the pod hit the memory limits. We are running the router in a k8s cluster so here are the resources before the update which were fine for the older router version:

```
resources:
   requests:
        cpu: 400m
        memory: 256Mi
   limits:
        cpu: 1000m
        memory: 600Mi
```

Now memory utilization increased to around 1000Mi. Do you have an explanation for this? 

## Environment
Kubernetes 1.25
