### ISSUE TITLE
Forward HTTP Authorization header on wundergraph router

### ISSUE THREAD

**Issue by miguelwebtales** [wundergraph/cosmo#873]
### Is your feature request related to a problem? Please describe.

I can't forward Authorization header using the configuration in the sample bellow

```
headers:
  all: # Header rules for all subgraph requests.
    request:
      - op: "propagate"
        named: authorization 
        rename: "authorization"`
```

### Describe the solution you'd like

In case no [authentication](https://cosmo-docs.wundergraph.com/router/authentication-and-authorization) configuration is provided to the router it should be allowed to forward the header "authorization"
