### ISSUE TITLE
wgc CLI does not respect @inaccessible entities

### ISSUE THREAD

**Issue by thekevinbrown** [wundergraph/cosmo#901]
### Component(s)

cli

### Component version

0.94.2

### wgc version

0.57.7

### controlplane version

N/A

### router version

0.94.2

### What happened?

If possible, please create a PR with a failing test to illustrate the issue clearly.
Otherwise, please attach a minimum reproduction through a GitHub repository that includes
essential information such as the relevant subgraph SDLs.
Please also make sure that the instructions for the reproduction are clear, tested, and fully accurate.

## Description

One of my entities looks like this:

```graphql
type AdminUiEntityAttributeMetadata @inaccessible {
  isReadOnly: Boolean
  exportPageSize: Float
}
```

When I run
```console
wgc router compose -i compose.yaml -o config.json
```

I get this:
```console
Failed to compose: Error: The object "AdminUiEntityAttributeMetadata" defines the same fields in multiple subgraphs without the "@shareable" directive:
 The field "isReadOnly" is defined in the following subgraphs: "music", "payments".
 However, it is not declared "@shareable" in any of them.

 The field "exportPageSize" is defined in the following subgraphs: "music", "payments".
 However, it is not declared "@shareable" in any of them.
```

As I understand it, this entity should not be processed by the supergraph at all, and should instead be completely ignored.

## Steps to Reproduce

1. Use `@inaccessible` on an entity in two subgraphs
2. Run `wgc router compose -i compose.yaml -o config.json`

## Expected Result

Expected successful composition omitting the entity.

## Actual Result

```console
Failed to compose: Error: The object "AdminUiEntityAttributeMetadata" defines the same fields in multiple subgraphs without the "@shareable" directive:
 The field "isReadOnly" is defined in the following subgraphs: "music", "payments".
 However, it is not declared "@shareable" in any of them.

 The field "exportPageSize" is defined in the following subgraphs: "music", "payments".
 However, it is not declared "@shareable" in any of them.
```

## Environment
OS: MacOS 14.5 (23F79)
Package Manager: pnpm version 8.15.8

### Router configuration

```yaml
version: 1
subgraphs:
  - name: music
    routing_url: http://localhost:9001
    introspection:
      url: http://localhost:9001
  - name: payments
    routing_url: http://localhost:12346
    introspection:
      url: http://localhost:12346
```
