### ISSUE TITLE
IntrospectionQuery is causing huge memory consumption after the latest updates

### ISSUE THREAD

**Issue by flymedllva** [wundergraph/cosmo#959]
### Component(s)

router

### Component version

0119c2d656674c07dde45372298a7b6ab625e70f

### wgc version

0.58.5

### controlplane version

-

### router version

0119c2d656674c07dde45372298a7b6ab625e70f

## Description

After one of the recent Cosmo updates, there is an abnormal increase in memory consumption when calling `IntrospectionQuery` (e.g. in the Playground refresh button).

Our schema (config.json), from which we get this result, weighs `13.7M`. On older versions of cosmo we didn't have this problem. 

Occurs after executing `err = t.loader.LoadGraphQLResponseData(ctx, response, t.resolvable)` in `resolve.go` (wundergraph/graphql-go-tools/v2@v2.0.0-rc.63)

## Steps to Reproduce

- Prepare a huge scheme
- Prepare a config from that schematic
- Run the cosmo with this config
- Press the refresh button in Playground

## Expected Result

Consume the normal amount of memory for this request)

## Actual Result

Brutal memory consumption)

https://github.com/user-attachments/assets/4793a6be-76a3-4647-91e3-667967081b5d

## Environment
OS: (e.g., "Ubuntu 20.04") macOS / Linux
Package Manager: npm
Compiler(if manually compiled): go version go1.22.3 darwin/arm64

### Router configuration

```yaml
version: "1"

# General router options
graph:
  name: "production"
  token: ""

log_level: "info"
listen_addr: "localhost:3002"
playground_enabled: true
introspection_enabled: true
json_log: true
shutdown_delay: 15s
grace_period: 20s
poll_interval: 10s
health_check_path: "/health"
readiness_check_path: "/health/ready"
liveness_check_path: "/health/live"
router_config_path: "config.json"

cors:
  allow_origins: ["*"]
  allow_methods:
    - HEAD
    - GET
    - POST
  allow_headers:
    - Origin
    - Content-Length
    - Content-Type
  allow_credentials: true
  max_age_minutes: 5m

# Config for custom modules   
# See "https://cosmo-docs.wundergraph.com/router/custom-modules" for more information   
modules:
  myModule:
    # Arbitrary values, unmarshalled by the module
    value: 1
```
