### ISSUE TITLE
For subscriptions, router should auto re-connect after subgraph server restarts

### ISSUE THREAD

**Issue by agufagit** [wundergraph/cosmo#972]
### Component(s)

router

### Component version

v0.98.2

### wgc version

v0.58.5

### controlplane version

n/a

### router version

v0.98.2

## Description
For subscriptions, router doesn't auto re-connect when subgraph server restarts

## Steps to Reproduce
1. open a websocket connection to router, make a subscription call, router will open a new websocket connection to subscription subgraph server
2. restart subscription subgraph server

## Expected Result
1. router auto re-connects to subscription subgraph server, open a new websocket connection and remake that subscription call

## Actual Result
1. the websocket connection between router and subscription subgraph server is gone

## Environment
OS: Ubuntu 20.04
Package Manager: pnpm
Compiler: go 1.22

### Router configuration

```yaml
dev_mode: true
listen_addr: 0.0.0.0:3009
router_config_path: config_dev.json
authentication:
  providers:
    - name: Auth Provider
      jwks: # JWKS provider configuration
        url: http://auth-gateway:8085/.well-known/jwks.json
        header_names: [Authorization]
        header_value_prefixes: [Bearer]
        refresh_interval: 2h
authorization:
  require_authentication: true
websocket:
  absinthe_protocol:
    enabled: false
file_upload:
  enabled: true
  max_file_size: 50MB
  max_files: 2
graph:
  # Result of `wgc router token create`. Can be omitted for local testing.
  token: ""
```

### Router execution config

```json
I'm testing locally.  I'm using custom modules, so I'm building router image locally.  Custom module code just maps JWT claims information to headers of subgraph requests
```
