### ISSUE TITLE
How to run a router without controlplain?

### ISSUE THREAD

**Issue by flymedllva** [wundergraph/cosmo#992]
### Component(s)

router

### Is your feature request related to a problem? Please describe.

We don't use controlplane, we build our own config.json and decide what to run the router with
After trying to run a new version of cosmo, an error pops up that controlplane must be specified.
In the documentation controlplane became mandatory for some reason.
![Screenshot 2024-08-01 at 15 58 08](https://github.com/user-attachments/assets/88857b03-062a-4f1e-8df1-faf6e8e38be2)

With what configuration is it now correct to run just the router (without other movable parts like controlplane)?
What config to use?

### Describe the solution you'd like

-

**Comment by flymedllva** [comment]
It feels like I now have to use the `router_registration` config, which is not described in the documentation

**Comment by jensneuse** [comment]
Definitely not intentional. We're taking a look.

**Comment by StarpTech** [comment]
Hi @flymedllva, please share your whole router config.

**Comment by flymedllva** [comment]
All the Issues I send were with the same config (below), but it stopped running and I haven't figured out how to run in the same config after the changes

```
version: "1"

# General router options
graph:
  name: "production"
  token: ""

log_level: "info"
listen_addr: "localhost:3002"
playground_enabled: true
introspection_enabled: true
json_log: true
shutdown_delay: 15s
grace_period: 20s
poll_interval: 10s
health_check_path: "/health"
readiness_check_path: "/health/ready"
liveness_check_path: "/health/live"
router_config_path: "config.json"

cors:
  allow_origins: ["*"]
  allow_methods:
    - HEAD
    - GET
    - POST
  allow_headers:
    - Origin
    - Content-Length
    - Content-Type
  allow_credentials: true
  max_age_minutes: 5m

# Config for custom modules   
# See "https://cosmo-docs.wundergraph.com/router/custom-modules" for more information   
modules:
  myModule:
    # Arbitrary values, unmarshalled by the module
    value: 1
```
